### ISSUE TITLE
the score seems incorrect

### ISSUE THREAD

**Issue by RayJueZhu** [by2101/OpenASR#2]
![Screenshot from 2020-03-25 23-40-42](https://user-images.githubusercontent.com/59601122/77555757-976f0d80-6ef2-11ea-8b9b-13b9dc98198b.png)
i suspect that the aishell.txt in exp is the problem.when i use decode_test.sh,the argument:exp/aishell.txt is the text i donnt have.so i argue it seems the vocab_file argument and then i use the aishel1_train_chars.txt instead and then it happens.
How can i do to solve it?
我发现在decode_test.sh的参数中我没有aishell.sh，于是我用了同在一个目录下的aishel1_train_chars.txt代替，因为我觉得这个参数对应这vocab_file这个参数，这样就造成了上述的情况，请问我错在什么地方？应该怎么修改？
（Ps: Thanks for giving the avg_last_ckpts.py!）

**Comment by RayJueZhu** [comment]
aishell.txt

**Comment by RayJueZhu** [comment]
Also,the score.sh is in need.Please.score.sh文件似乎也缺失，希望能提供一下，谢谢了

**Comment by by2101** [comment]
你好，score.sh 我传上去了。解码结果我得复现一下看看。你训练的loss降到多少了？

**Comment by by2101** [comment]
> Also,the score.sh is in need.Please.score.sh文件似乎也缺失，希望能提供一下，谢谢了


> aishell.txt

谢谢，有一些名字我确实打错了。

**Comment by RayJueZhu** [comment]
我运行了一下，好像结果不是很对，我再运行一次看看
[result.txt](https://github.com/by2101/OpenASR/files/4385397/result.txt)

**Comment by by2101** [comment]
> 我运行了一下，好像结果不是很对，我再运行一次看看
> [result.txt](https://github.com/by2101/OpenASR/files/4385397/result.txt)

你可以先看看loss降得对不对。cv loss应该在0.4左右

**Comment by RayJueZhu** [comment]
我这边CV LOSS的确是0.4但是在进行decode_test的时候依然一样的结果
如果不是模型的问题，那是什么问题呢
![Screenshot from 2020-03-26 23-08-25](https://user-images.githubusercontent.com/59601122/77663242-d0bd8100-6fb7-11ea-9f53-5797d63ac9e2.png)

**Comment by RayJueZhu** [comment]
[[[ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]]

 [[ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]]

 [[ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]]

 ...

 [[ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]]

 [[ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]]

 [[ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]
  [ 1  7 15 ...  0  0  0]]]

我发现我这边运行decode.py的时候，all_ids_batch这个的值永远是上面的情况，这么说：
with torch.no_grad():
            target_ids, scores = model.decode(padded_waveforms, wave_lengths, nbest_keep=args.nbest, maxlen=args.maxlen)
这句的结果是有问题的么？

**Comment by RayJueZhu** [comment]
为什么beam_search出的target_ids会全是1 7 15……这些呢，训练的模型有问题么，望详解，感谢了。还有LM似乎在base的声学模型后没有运用吧？那怎么才能一起使用呢？

**Comment by by2101** [comment]
> 为什么beam_search出的target_ids会全是1 7 15……这些呢，训练的模型有问题么，望详解，感谢了。还有LM似乎在base的声学模型后没有运用吧？那怎么才能一起使用呢？

LM 的Shallow Fusion这个代码还没加进去，后边我会加进去。现在主要是为了使用LST training。训练的问题我这边正在重跑看看。

**Comment by RayJueZhu** [comment]
静候佳音，我自己也再找找我这边的原因，谢谢了

**Comment by by2101** [comment]
> 静候佳音，我自己也再找找我这边的原因，谢谢了

我更新了config_base.yaml，跑出来解码没有问题。你再试试。
