### ISSUE TITLE
请问下您的复现成功了么？

### ISSUE THREAD

**Issue by RayJueZhu** [by2101/OpenASR#3]
我这边又跑了一边，还是decode的结果不对……无论是测试哪一段音频，decode结果都是同一句话，请问我应该如何修改呢？

**Comment by by2101** [comment]
我这边成功的呀。我push了两个log文件你看看。因为最近没有时间，只train到45epoch，decode了几个句子。

**Comment by by2101** [comment]
请查看最新的commit

**Comment by RayJueZhu** [comment]
我这个步骤有什么问题么，我是自己下载的aishell，然后把prep_data.sh里的步骤拆开来独自运行，先download_and_untar.sh，解压缩，然后用aishell_data_prep.sh把各个数据集分好，然后运行prep_data.sh,之后就train.sh base,然后avg.sh,然后decode_test.sh,这个decode_test.sh就是出现之前decode结果一直是同一句话的问题，您觉得我这边可能哪里有问题呢？

**Comment by RayJueZhu** [comment]
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
我这边train的时候，一直有这个warning，但是我觉得这个肯定没影响吧？
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
2020-03-29 18:21:32,081 - /home/rayjue/Documents/ASR/OPENASR/OpenASR/src/trainer.py[line:278] - INFO: Progress:
Epoch 1 | Step 55 | Iter 440:
per_token_loss: 8.0728951 | avg_token_loss: 8.3497334 | learning_rate: 0.0000012
sequence_per_sec: 74.3903573

**Comment by by2101** [comment]
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> 我这边train的时候，一直有这个warning，但是我觉得这个肯定没影响吧？
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (masked_fill__cuda at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19)
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> 2020-03-29 18:21:32,081 - /home/rayjue/Documents/ASR/OPENASR/OpenASR/src/trainer.py[line:278] - INFO: Progress:
> Epoch 1 | Step 55 | Iter 440:
> per_token_loss: 8.0728951 | avg_token_loss: 8.3497334 | learning_rate: 0.0000012
> sequence_per_sec: 74.3903573

这个warning没有关系。这个是因为torch 1.2以后加了一个bool的类型。
那你看看你最终训练的cv loss是多少，应该在0.4左右。如果没有到，有可能训练失败了，那么就把warmup step设置的更大一些。

**Comment by RayJueZhu** [comment]
看了一下您的log，为什么我这边运行到第8个epoch之后，就自动停止了呢？是因为显存不足么？

**Comment by RayJueZhu** [comment]
上次就运行到了epoch 8，loss 5，确实不正确，那我要怎么避免他会停止运行的情况呢？

**Comment by RayJueZhu** [comment]
这边是用1070训练的，8G显存是瓶颈么？

**Comment by by2101** [comment]
> 这边是用1070训练的，8G显存是瓶颈么？

有可能。你可能需要减小batch size，增加 accumu grad步数。cv loss得达到零点几才能正确解码。

**Comment by by2101** [comment]
> 上次就运行到了epoch 8，loss 5，确实不正确，那我要怎么避免他会停止运行的情况呢？

如果已经跑了几个epoch，那应该可以顺利运行。可以给train.py 设置参数 --continue-training True，就会继续训练了。

**Comment by RayJueZhu** [comment]
感谢了，就是调整accumulate_grad_batch，和batch_time,还有 --continue-training True了吧，这里有个疑问，似乎我应该减小batch_time，增大accumulate_grad_batch么？这两个参数和batch_size有什么关系？

**Comment by by2101** [comment]
> 感谢了，就是调整accumulate_grad_batch，和batch_time,还有 --continue-training True了吧，这里有个疑问，似乎我应该减小batch_time，增大accumulate_grad_batch么？这两个参数和batch_size有什么关系？

batch time是gpu一次计算的语音的总时长。一般需要batch大一点训练才稳定，但是我们的GPU显存又往往不够大：P，所以利用accumulate_grad_batch累积梯度来模拟大batch。总的batch=batch_time*accumulate_grad_batch

**Comment by RayJueZhu** [comment]
那我注意到，整个aishell的训练集的总时长是没有150h小时的，也就是说，一次计算就把训练集全部投入了，那么batch_time是一个不好变动的量，可以这么理解么？如果大一点的batch才能稳定，那么又不能把accumulate_grad_batch直接设置的比较小，所以把accumulate_grad_batch先设为6，可以一试的吧？另外，关于卡在epoch 8就停止的说法，我这边已经在上次的基础上继续跑了，如果epoch 16附近依然停止 ，那看来就是显存的问题了。。。

**Comment by by2101** [comment]
没有一次性投入，batch_time是一个batch的时长，单位是秒

**Comment by RayJueZhu** [comment]
我傻了hh,aishell这么大，怎么可能一次性全部载入，那我明白了。

**Comment by RayJueZhu** [comment]
感谢啦，确实是显存不足的问题，建议您在README里面补充一下您的配置和我这种配置不足的情况，这边运行到epoch 17果然停止运行了

**Comment by RayJueZhu** [comment]
但是，看卡顿的情况，我感觉也有可能是内存的原因
