### ISSUE TITLE
how to train lst acoustic model

### ISSUE THREAD

**Issue by panxin801** [by2101/OpenASR#5]
Hi, can you figure me out how to use config_lst.yaml for training acoustic model ?

**Comment by by2101** [comment]
First, you need to train rnnlm. 
see config_lst.yaml, set lst weight and lst temporature.
However, if you want to have good performance with lst, the two parameters need to be tune. and external text is needed.

I will provide new recipe after I finish my new work on LST.

**Comment by panxin801** [comment]
In fact, I watch train.sh in `OpenASR/egs/aishell1/s5` I see the config_lst.yaml and `elif [ "$sys_tag" == "lst" ]; then` in train.sh but I don't see anything about how to use config_lst.taml for help

**Comment by by2101** [comment]
config_lst.yaml just adds lst configuration in the yaml. you can see the last lines in the yaml.

**Comment by panxin801** [comment]
OK thank you
